language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

script:
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then mvn clean source:jar javadoc:javadoc deploy --settings travis_settings.xml; fi'
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "false" ]; then mvn clean verify; fi'

# travis encrypt -r bootique/bootique-undertow "CI_DEPLOY_USERNAME='name'"
# travis encrypt -r bootique/bootique-undertow "CI_DEPLOY_PASSWORD='password'"
env:
  global:
    - secure: "gE+47oFKzu5iLtL9g+j7Gzyk4wLcmQhceO8mA74vTTbYbRi13yEc0866PYJy6H8ylRW3pbysVmzbS17CZ0WF7bjghA12+LeGtHsRgok/o50AvaJxnyoK3taSE8f71bER67TSeqYSCNS5G8tOCtLGm2O7TCW/HM28qIcEAAHRY85Pqw3hMAh6JUU5qQkqgXD7sbt7h09oELjDFpfQDxSQwCajNAfaAYj8CiTVzYw3JPJUtBs9jCpV1SqiNRFo1DT+I8oxmcRGExN/f/6XR9wrre4/AWSXzd1RGeQzDCkIK+TsGpiecGwdrMIfrnysgJXhKKf9Aw+NgoPuN709npqeELTNiNHSrafJ9NtjjgE604B3df6tfEGwe0bVkXrzGw6ac7NfMmOuDMElxb7VEOLJSZ/r0jbQxP9ZP4devy6N0/mbcTs6MHmcHQ1iaYCwfdxhKT6Eu5tvFrUAUdb4XGRYNjPJDDlTs/HYeZ+S8/6pVC57GYsLNagXp94/uBpIEyCvD+2ARXA4d60BNGPJXKFUpG+BhZq9iisa8EIrdNr9zlVJUJ4yvAOSse3//THOhWPNy0wQZlahNqPzwjSygFRsbPIHlJI5mICWlSeWKfpWlGqnF6iArbrAvX/vWf71yxgWLSqkUtkepaZlKaC9tTbbiBXymEBfKPN/tNi7eK3rfm8="
    - secure: "KVkrdiXeiNET0Nz8bxeasT056EpZel0yMliOjWjabOLFV1ppQjA3KhWplJF3OMLKg25HwDvar05Z1eFnDgic24UV4j489byPNgRwbo3Awt534jPfhF0X/mokI7lwl2QPwj6hE78sdpJDWzfI7R9hHF12qakfAcZMikVDdWruYRhIbm++QlO0IthVF5NTBDOup/jrxKqwMPFCd5uNo+l1Xv1fislk09YRF32UJC3ocgCSUSdMrXSRMqrxzhnx9Do3aWuI7hQwuraC4L9RGzne23h/AtoAzsITNNLDcpIM+4/qpszxEnnrw1y3RNJ9PgnxpPbjWX3/CA6JLmkt4e2w+orEnnF2o6Q17ukU9TuX2OnkHxq55vsLDVMmt/8DIktiGzXK75HAnT8ziqxAAYchQxwM24MTYjx8hpinxddJpHL5sL29fjrRdnmXqED+GxV1NVBKzxjsbaO22OVMJdgG2oOI2iZKkh2MJP3swrV5GBVP+g0F8kzU5/NV7T31p1iIhEZTpu3VXhkIO+jU0sbe7ggcmKMehLhylwUOrwK9/uXjJE1kf9le2JkiA0IyL8u34owh1QGC4g85nM11m7uFtDvFOBnQ0RmaSg+TpZBUiG9zL17F/F5/CGj4Xli4J6wSQTgHEHGVEezERIjfl418a2CpZK/6Z47XqNmpuJPGvqw="
